name: Deploy Django App to GKE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: django-cluster
  GKE_ZONE: us-central1-a
  DEPLOYMENT_NAME: django-app
  IMAGE: django-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA .

    - name: Push Docker image
      run: |
        docker push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

    - name: Update deployment image
      run: |
        # Update the deployment with the new image
        sed -i "s|gcr.io/PROJECT_ID/django-app:latest|gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA|g" k8s/deployment.yaml

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/
        kubectl set image deployment/$DEPLOYMENT_NAME django-app=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA -n django-app
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n django-app

    - name: Run Django migrations
      run: |
        # Get the first pod name
        POD_NAME=$(kubectl get pods -n django-app -l app=django-app -o jsonpath='{.items[0].metadata.name}')
        kubectl exec -n django-app $POD_NAME -- python manage.py migrate

    - name: Verify deployment
      run: |
        kubectl get services -n django-app
